[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_lib"
crate-type = ["cdylib"]  # This ensures it builds as a shared library compatible with C

[dependencies]
rand = "0.8"

[target.'cfg(target_os = "macos")'.dependencies]